### ISSUE TITLE
Description of sniffs

### ISSUE THREAD

**Issue by szepeviktor** [FloeDesignTechnologies/phpcs-security-audit#23]
Is there a summary what these sniffs mean, and how to resolve them?
Thanks.

**Comment by jmarcil** [comment]
Hello,

thanks for your interest in this tool. Unfortunately, there's nothing more than what is in the code. I understand that's virtually none.

The original goal of this tool was not to document vulnerabilities in PHP but rather pointing to sensitive and risky code. In order to ensure your code is less at risk, you either refrain from using sensible functions in common code and leave that to a framework, or you learn about why and make sure it is robust. Security is not an easy thing so there's no easy answer for everyone on every findings.

We're going to try to have better in-line explanation when issues are found. If you want to contribute check out the thread on #28.

Thanks!

**Comment by szepeviktor** [comment]
Thank you for your answer.
