### ISSUE TITLE
phpcs built from Dockerfile gives an error

### ISSUE THREAD

**Issue by nikitastupin** [FloeDesignTechnologies/phpcs-security-audit#62]
Hi,

I've just built phpcs from master 66845e0efab9ae09ae6545c1e49455151468b49a using `docker build -t phpcs .`. After I'm running it with `docker run -i -t --rm -v "$(pwd)":/opt/mount phpcs` I'm getting  `ERROR: Referenced sniff "Security.BadFunctions.Asserts" does not exist`. 

It looks like bug was introduced in c36e8c6fae2be53b37e361e7e314302de0fbeb5c since I've just build & run suing the same commands but from b16843d48abb1809159eb500a51c5153e1ed8e31 (it's a commit right before c36e8c6fae2be53b37e361e7e314302de0fbeb5c) and all works OK.

## Environment

* macOS 10.15.3
* Docker version 19.03.5, build 633a0ea

**Comment by jrfnl** [comment]
@nikitastupin I know virtually nothing about Docker, but I can tell you that the install instructions have changed with https://github.com/FloeDesignTechnologies/phpcs-security-audit/commit/c36e8c6fae2be53b37e361e7e314302de0fbeb5c, which will be in the next major.

Did you update your Docker build script with the new install instructions ?

**Comment by jmarcil** [comment]
That error can be when it cannot find the phpcs sniff due to wrong installed_paths. By default it is a relative path, and might work better if we set something absolute in Docker.

Can you try to add this line before `WORKDIR /tmp` in the Dockerfile:
```
RUN /tmp/vendor/bin/phpcs --config-set installed_paths /tmp/vendor/pheromone/phpcs-security-audit/
```

**Comment by jrfnl** [comment]
@jmarcil That shouldn't be needed as the `dealerdirect/phpcodesniffer-composer-installer` composer plugin should set that automatically.

@nikitastupin What does `phpcs -i` return ?

**Comment by nikitastupin** [comment]
> https://github.com/FloeDesignTechnologies/phpcs-security-audit/issues/62#issuecomment-587585144

I've added this line and error gone!

> What does phpcs -i return ?

`The installed coding standards are MySource, PEAR, PSR12, PSR2, Zend, Squiz and PSR1`

**Comment by jrfnl** [comment]
> 
> `The installed coding standards are MySource, PEAR, PSR12, PSR2, Zend, Squiz and PSR1`

Hmm.. that doesn't look right... in that case you should still get the error. Could it be that there are multiple PHPCS installs in the image ? and that this one is a different one from the one containing the Security standard ?

**Comment by nikitastupin** [comment]
> Hmm.. that doesn't look right... in that case you should still get the error. Could it be that there are multiple PHPCS installs in the image ? and that this one is a different one from the one containing the Security standard ?

I did `phpcs -i` on image that _returns the error_ :)

After that I've added `RUN /tmp/vendor/bin/phpcs --config-set installed_paths /tmp/vendor/pheromone/phpcs-security-audit/` to Dockerfile and error has gone!

**Comment by jmarcil** [comment]
@nikitastupin can you create a pull request with that fix? I'll promptly merge it.

**Comment by nikitastupin** [comment]
Done #64

**Comment by jmarcil** [comment]
OK now master should be "fixed". I've done this just to have a working state as I'm not sure when this will be properly fixed.

My take on this is that phpcodesniffer-composer-installer doesn't work properly within our Docker environment and it's probably setting the wrong `installed_paths` for whatever reason.

I still haven't created/tested any composer package with what we have so far, so maybe that's a problem regardless of Docker.

Also, I noticed that in the instruction we're supposed to do `--dev` (but yet we don't use require-dev in composer.json?) and the docker file doesn't do `--dev`. Maybe that's why phpcodesniffer-composer-installer is ineffective?

@nikitastupin I'll close this issue, as the bug is resolved with your PR, but I'd appreciate a lot if you could figure out (maybe with some help from @jrfnl) what is wrong with Docker / our package right now.
